language: python
sudo: false
env:
  - BOTO_CONFIG=/dev/null
python:
  - "3.6"
install:
  - sudo apt install mecab libmecab-dev mecab-ipadic
  - python setup.py develop -q
before_script: cd tests
script:
  - pip freeze
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pytest --runintegration; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then pytest; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then pip install black; black --check .; fi'
