[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.pytest_cache
    | build
    | dist
  )/
)
'''
[tool.pytest.ini_options]
flake8-max-line-length = 210
flake8-ignore = ["E203", "W503"]  # See https://github.com/PyCQA/pycodestyle/issues/373
addopts = "--flake8 --mypy --isort"
filterwarnings = [
    "error",  # Convert all warnings to errors
    'ignore:torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables',  # Distilbert warning
    'ignore:TorchScript will treat type annotations of Tensor:UserWarning',  # Torch onnx export warns about it ignoring types, however we still like types.
    'ignore:Please use `triu` from the `scipy.linalg` namespace, the `scipy.linalg.special_matrices` namespace is deprecated.',  # ignore gensim using deprecated scipy
    'ignore:bilinear is deprecated and will be removed in Pillow 10',  # huggingface layoutlmv2 has deprecated calls.
    'ignore:nearest is deprecated and will be removed in Pillow 10',  # huggingface layoutlmv2 has deprecated calls.
    'ignore:The `device` argument is deprecated and will be removed in v5 of Transformers.',  # hf layoutlmv3 calls deprecated hf.
    "ignore:the imp module is deprecated:DeprecationWarning:past",  # ignore DeprecationWarning from hyperopt dependency
    "ignore:.*imp module.*:DeprecationWarning",  # ignore DeprecationWarnings that involve imp module
]
markers = [
    "integration",
]
testpaths = ["flair", "tests"]
[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module="flair.embeddings.legacy"
ignore_errors = true

[tool.isort]
profile = "black"
