on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TRANSFORMERS_CACHE: ./cache/transformers
      FLAIR_CACHE_ROOT: ./cache/flair
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Flair dependencies
        run: pip install -e .
      - name: Install unittest dependencies
        run: pip install -r requirements-dev.txt
      - name: Show installed dependencies
        run: pip freeze
      - name: Cache downloaded models/datasets
        uses: actions/cache@v3
        with:
          path: ./cache
          key: cache-v1.1
      - name: Run tests
        run: pytest --runintegration --durations=0 -vv
  test_install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install Flair dependencies
        run: pip install .
      - name: Install unittest dependencies
        run: pip freeze
      - name: Test import
        run: |
          cd resources
          python -c "import flair"